accent = "#dfb8f6"
cursor = "#e9e0e8"
foreground = "#e9e0e8"
background = "#161217"
selection_foreground = "#161217"
selection_background = "#dfb8f6"

color0 = "#161217"
color1 = "#ffb4ab"
color2 = "#b4d1b6"
color3 = "#e4c3a2"
color4 = "#dfb8f6"
color5 = "#e9b3f8"
color6 = "#a1d0db"
color7 = "#e9e0e8"
color8 = "#4b454d"
color9 = "#ffb4ab"
color10 = "#b4d1b6"
color11 = "#e4c3a2"
color12 = "#dfb8f6"
color13 = "#e9b3f8"
color14 = "#a1d0db"
color15 = "#cdc3ce"
