include=~/.local/share/omarchy/default/mako/core.ini

# History
history=1
max-history=100

# Theme colors (auto-updated by theme-set hook)
text-color=#ffffff
border-color=#8d8d8d
background-color=#000000

# Appearance
border-radius=6
